export const GUIDE_CATEGORIES = [
  { id: "using-page-watch", label: "Using Page Watch" },
  { id: "monitoring", label: "Monitoring" },
  { id: "page-status", label: "Page status" },
  { id: "scores-evidence", label: "Scores & evidence" },
  { id: "recommendations-tasks", label: "Recommendations & tasks" },
  { id: "access-roles", label: "Access & roles" },
] as const;

export type GuideCategoryId = (typeof GUIDE_CATEGORIES)[number]["id"];

export interface GuideEntry {
  id: string;
  term: string;
  shortDefinition: string;
  category: GuideCategoryId;
  appMeaning: string;
  action?: string;
  related?: string[];
  aliases?: string[];
}

export const GUIDE_ENTRIES: GuideEntry[] = [
  {
    id: "dashboard",
    term: "Dashboard",
    shortDefinition: "The at-a-glance view of the pages that need your attention.",
    category: "using-page-watch",
    appMeaning: "The Dashboard combines current Performance trends, visitor experience, agent-readiness gaps, and the most important recommendations across the project.",
    action: "Start here to find regressions, low-performing pages, and high-priority fixes.",
    related: ["Pages", "Page status", "Visitor experience"],
  },
  {
    id: "pages",
    term: "Pages",
    shortDefinition: "A sortable view of every page in the current project.",
    category: "using-page-watch",
    appMeaning: "The Pages area shows each watched URL and its latest mobile, desktop, Performance, accessibility, Best Practices, SEO, and agent-readiness signals.",
    action: "Open a page to investigate its history, evidence, recommendations, and change markers.",
    related: ["Dashboard", "Watchlist", "Page detail"],
  },
  {
    id: "page-detail",
    term: "Page detail",
    shortDefinition: "The full monitoring record for one page.",
    category: "using-page-watch",
    appMeaning: "A page detail view brings together score history, device trends, visitor evidence, diagnostics, recommendations, agent readiness, and recorded changes.",
    action: "Use it when you need to understand why a page changed or what to do next.",
    related: ["Pages", "Change marker", "Recommendation"],
  },
  {
    id: "inbox",
    term: "Inbox",
    shortDefinition: "New recommendations waiting for a decision.",
    category: "using-page-watch",
    appMeaning: "Page Watch places actionable findings in the Inbox so they can be reviewed before becoming committed work.",
    action: "Review each recommendation and turn it into a task or ignore it when it is not relevant.",
    related: ["Recommendation", "Tasks", "Ignored"],
  },
  {
    id: "tasks",
    term: "Tasks",
    shortDefinition: "Recommendations your team has committed to addressing.",
    category: "using-page-watch",
    appMeaning: "Tasks retain the recommendation evidence while adding a simple To do, In progress, and Done workflow.",
    action: "Move work through the task statuses. Marking a task Done records a change marker and enables follow-up comparisons.",
    related: ["Recommendation", "Change marker", "Done"],
  },
  {
    id: "watchlist",
    term: "Watchlist",
    shortDefinition: "The set of pages Page Watch is configured to monitor.",
    category: "using-page-watch",
    appMeaning: "Project administrators use the Watchlist to add, reorder, pause, prioritize, and configure page-specific monitoring thresholds.",
    action: "Keep the list focused on pages whose performance and readiness matter to the project.",
    related: ["Watching", "Priority", "Paused"],
  },
  {
    id: "baseline",
    term: "Baseline",
    shortDefinition: "The intentional starting point used to judge later measurements.",
    category: "monitoring",
    appMeaning: "A baseline stores the initial trusted mobile and desktop scores for a page. Ordinary runs do not silently create or replace it.",
    action: "Capture a baseline after adding a page and when the page is in a representative state.",
    related: ["Pending", "On-demand run", "Performance trend"],
  },
  {
    id: "on-demand-run",
    term: "On-demand run",
    shortDefinition: "A measurement you start manually instead of waiting for the schedule.",
    category: "monitoring",
    appMeaning: "It collects the same core Lighthouse, agent-readiness, and diagnostic evidence as scheduled monitoring without replacing the baseline.",
    action: "Run a page after a meaningful change when you want evidence sooner than the next nightly run.",
    related: ["Nightly run", "Collection", "Baseline"],
  },
  {
    id: "nightly-run",
    term: "Nightly run",
    shortDefinition: "The project’s automatically scheduled daily collection.",
    category: "monitoring",
    appMeaning: "Active pages receive a stable offset inside the project’s configured local-time collection window. Results update history, statuses, and recommendations.",
    action: "Check the schedule in the sidebar or Settings; use an on-demand run when you cannot wait.",
    related: ["On-demand run", "Collection", "Watching"],
  },
  {
    id: "collection",
    term: "Collection",
    shortDefinition: "The process of gathering and saving a page’s measurement evidence.",
    category: "monitoring",
    appMeaning: "A collection coordinates repeated mobile and desktop tests, removes untrustworthy samples, scans agent readiness, gathers diagnostics, and commits a result only when enough evidence is available.",
    action: "Let an active collection finish before starting another run for the same page.",
    related: ["Reliable", "Inconclusive", "Lighthouse"],
  },
  {
    id: "queued",
    term: "Queued",
    shortDefinition: "The collection has been accepted and is waiting to start.",
    category: "monitoring",
    appMeaning: "Page Watch has reserved the job, but the collector has not started its measurement work yet.",
    action: "No action is normally needed.",
    related: ["Dispatching", "Running"],
  },
  {
    id: "dispatching",
    term: "Dispatching",
    shortDefinition: "The collection is being handed to the background workflow.",
    category: "monitoring",
    appMeaning: "This is the brief transition between reserving a collection and running its tests.",
    action: "No action is normally needed.",
    related: ["Queued", "Running"],
  },
  {
    id: "running",
    term: "Running",
    shortDefinition: "The collector is actively measuring the page.",
    category: "monitoring",
    appMeaning: "Mobile and desktop samples or related evidence are currently being gathered.",
    action: "Wait for the run to complete before judging the page’s latest status.",
    related: ["Waiting for evidence", "Succeeded"],
  },
  {
    id: "waiting-for-evidence",
    term: "Waiting for evidence",
    shortDefinition: "The collection needs another independent measurement before it can finish.",
    category: "monitoring",
    appMeaning: "The durable workflow is waiting before retrying because one or both devices do not yet have enough trustworthy samples.",
    action: "No immediate action is needed; Page Watch retries automatically.",
    related: ["Running", "Inconclusive", "Reliable"],
  },
  {
    id: "succeeded",
    term: "Succeeded",
    shortDefinition: "The collection completed with enough evidence to save a trusted result.",
    category: "monitoring",
    appMeaning: "The scores and associated evidence were committed to the page’s history.",
    action: "Review any resulting status changes or new recommendations.",
    related: ["Collection", "Reliable", "Recommendation"],
  },
  {
    id: "inconclusive",
    term: "Inconclusive",
    shortDefinition: "The collection finished without enough trustworthy evidence for a result.",
    category: "monitoring",
    appMeaning: "Provider warnings, repeated cached measurements, or too few independent samples prevented Page Watch from committing scores.",
    action: "Try again later. If it repeats, investigate the page or measurement provider rather than treating it as a regression.",
    related: ["Waiting for evidence", "Unusable", "Failed"],
  },
  {
    id: "failed",
    term: "Failed",
    shortDefinition: "The collection stopped because it could not complete.",
    category: "monitoring",
    appMeaning: "A workflow, provider, page, or configuration error prevented successful completion.",
    action: "Read the displayed error, confirm the URL is reachable, and retry after correcting any known issue.",
    related: ["Inconclusive", "Collection"],
  },
  {
    id: "priority",
    term: "Priority",
    shortDefinition: "An actively monitored page marked as especially important.",
    category: "monitoring",
    appMeaning: "Priority distinguishes critical pages from the rest of the active watchlist without changing what evidence is collected.",
    action: "Use it for pages such as key landing, conversion, or high-traffic pages.",
    related: ["Watching", "Paused", "Watchlist"],
  },
  {
    id: "watching",
    term: "Watching",
    shortDefinition: "A page included in regular scheduled monitoring.",
    category: "monitoring",
    appMeaning: "Watching is the normal active state for a page on the watchlist.",
    action: "Leave a page Watching when it should continue receiving nightly measurements.",
    related: ["Priority", "Paused", "Nightly run"],
  },
  {
    id: "paused",
    term: "Paused",
    shortDefinition: "A page retained in the project but excluded from active monitoring.",
    category: "monitoring",
    appMeaning: "Its existing history remains available, but scheduled collection does not run while it is paused.",
    action: "Pause pages temporarily when they should not consume monitoring capacity; resume them when they matter again.",
    related: ["Watching", "Watchlist"],
  },
  {
    id: "pending",
    term: "Pending",
    shortDefinition: "There is not enough post-baseline history to classify the page trend.",
    category: "page-status",
    appMeaning: "Pending appears before the page has a usable baseline and enough later measurements for the selected device and range.",
    action: "Capture a baseline if needed, then allow the required follow-up runs to complete.",
    related: ["Baseline", "Stable", "Performance trend"],
  },
  {
    id: "stable",
    term: "Stable",
    shortDefinition: "Performance has not moved beyond the configured improvement or regression rules.",
    category: "page-status",
    appMeaning: "For the selected device and date range, the Performance score change remains within the project’s thresholds and observed run-to-run noise.",
    action: "No trend-based action is required, but low absolute scores and recommendations may still need attention.",
    related: ["Improving", "Regressing", "Performance trend"],
  },
  {
    id: "improving",
    term: "Improving",
    shortDefinition: "Performance increased enough to exceed the configured improvement threshold and observed noise.",
    category: "page-status",
    appMeaning: "The classification is calculated independently for mobile and desktop over the selected date range.",
    action: "Review recent change markers to understand what helped and confirm visitor experience where available.",
    related: ["Stable", "Regressing", "Change marker"],
  },
  {
    id: "regressing",
    term: "Regressing",
    shortDefinition: "Performance dropped enough to meet the project’s confirmed regression rules.",
    category: "page-status",
    appMeaning: "Page Watch evaluates the selected device and range using configured drop, floor, confirmation, and noise rules.",
    action: "Open the page, compare recent evidence with change markers, and triage actionable recommendations.",
    related: ["Stable", "Improving", "Recommendation"],
  },
  {
    id: "performance-trend",
    term: "Performance trend",
    shortDefinition: "The direction of a page’s Performance score over the selected date range.",
    category: "page-status",
    appMeaning: "Mobile and desktop are classified separately as Pending, Stable, Improving, or Regressing.",
    action: "Always note the selected device and range when interpreting a trend.",
    related: ["Page status", "Mobile", "Desktop"],
    aliases: ["Page status"],
  },
  {
    id: "lighthouse",
    term: "Lighthouse",
    shortDefinition: "Google’s automated lab test for page quality.",
    category: "scores-evidence",
    appMeaning: "Page Watch uses PageSpeed Insights to run Lighthouse repeatedly for mobile and desktop, then stores trusted median scores, ranges, warnings, and recurring findings.",
    action: "Use Lighthouse to reproduce issues consistently, but compare it with visitor evidence when available.",
    related: ["Lab data", "Visitor experience", "Median"],
  },
  {
    id: "lab-data",
    term: "Lab data",
    shortDefinition: "Measurements collected under controlled, repeatable test conditions.",
    category: "scores-evidence",
    appMeaning: "Lighthouse scores and diagnostics are lab data. They are useful for debugging and comparison but do not represent every real visitor.",
    action: "Use lab evidence to investigate causes; use visitor experience to understand real-world impact.",
    related: ["Lighthouse", "Visitor experience", "Lab and field"],
  },
  {
    id: "visitor-experience",
    term: "Visitor experience",
    shortDefinition: "Real-world performance evidence from Chrome users.",
    category: "scores-evidence",
    appMeaning: "Page Watch collects weekly Chrome UX Report rolling 28-day p75 metrics for phone and desktop, preferring exact-URL data and using origin data only as context when needed.",
    action: "Use it to confirm whether a lab finding affects real visitors. It changes more slowly than nightly lab data.",
    related: ["CrUX", "Lab data", "P75"],
    aliases: ["Field data", "Real-user data"],
  },
  {
    id: "crux",
    term: "CrUX",
    shortDefinition: "The Chrome UX Report, Google’s source of aggregated real-user performance data.",
    category: "scores-evidence",
    appMeaning: "CrUX supplies Page Watch’s visitor-experience metrics and Good, Needs improvement, or Poor ratings.",
    action: "Check whether evidence is exact-URL or origin-level before applying it to a specific page.",
    related: ["Visitor experience", "P75", "LCP"],
    aliases: ["Chrome UX Report"],
  },
  {
    id: "lab-and-field",
    term: "Lab and field",
    shortDefinition: "A comparison between controlled Lighthouse tests and real visitor evidence.",
    category: "scores-evidence",
    appMeaning: "Signals can be Aligned, Corroborated, Divergent, Partial, or Unavailable depending on whether both evidence systems exist and tell the same story.",
    action: "Prioritize corroborated problems. Investigate divergent results instead of assuming either source is wrong.",
    related: ["Lab data", "Visitor experience"],
  },
  {
    id: "mobile",
    term: "Mobile",
    shortDefinition: "The phone-oriented measurement strategy.",
    category: "scores-evidence",
    appMeaning: "Page Watch keeps mobile scores, history, status, findings, and visitor evidence separate from desktop.",
    action: "Use the device control to confirm which strategy you are viewing.",
    related: ["Desktop", "Performance trend"],
  },
  {
    id: "desktop",
    term: "Desktop",
    shortDefinition: "The desktop-oriented measurement strategy.",
    category: "scores-evidence",
    appMeaning: "Page Watch keeps desktop scores, history, status, findings, and visitor evidence separate from mobile.",
    action: "Review both devices; a problem on one does not guarantee the same result on the other.",
    related: ["Mobile", "Performance trend"],
  },
  {
    id: "median",
    term: "Median",
    shortDefinition: "The middle result from a group of trusted test runs.",
    category: "scores-evidence",
    appMeaning: "Page Watch uses medians instead of a single run to reduce the effect of unusually fast or slow measurements.",
    action: "Treat the median as the nightly score and use the range to understand variability.",
    related: ["Range", "Reliable", "Lighthouse"],
  },
  {
    id: "range",
    term: "Range",
    shortDefinition: "The lowest and highest trusted scores observed during a collection.",
    category: "scores-evidence",
    appMeaning: "The range reveals run-to-run variability that a median alone would hide.",
    action: "A wide range suggests noisy evidence; avoid overreacting to a small change inside that noise.",
    related: ["Median", "Low confidence"],
  },
  {
    id: "p75",
    term: "P75",
    shortDefinition: "The value that 75% of recorded visitor experiences were at or better than.",
    category: "scores-evidence",
    appMeaning: "CrUX uses the 75th percentile for Page Watch’s visitor metrics, helping represent the slower end of typical experiences without focusing only on extremes.",
    action: "Compare p75 values with their Good, Needs improvement, and Poor thresholds.",
    related: ["Visitor experience", "CrUX"],
    aliases: ["75th percentile"],
  },
  {
    id: "performance",
    term: "Performance",
    shortDefinition: "Lighthouse’s overall score for loading speed and runtime responsiveness.",
    category: "scores-evidence",
    appMeaning: "Page Watch uses the Performance category for page trends and combines it with detailed metrics and diagnostics.",
    action: "Use the score to spot movement, then inspect metrics and recommendations to find the cause.",
    related: ["LCP", "TBT", "CLS"],
    aliases: ["Perf"],
  },
  {
    id: "accessibility",
    term: "Accessibility",
    shortDefinition: "Automated checks for common barriers affecting people with disabilities.",
    category: "scores-evidence",
    appMeaning: "The Lighthouse Accessibility score covers detectable issues such as names, contrast, structure, and semantics. It is not a complete accessibility audit.",
    action: "Fix reported issues and supplement automated checks with manual and assistive-technology testing.",
    related: ["Best Practices", "SEO"],
    aliases: ["A11y"],
  },
  {
    id: "best-practices",
    term: "Best Practices",
    shortDefinition: "Lighthouse checks for general web quality, safety, and modern implementation practices.",
    category: "scores-evidence",
    appMeaning: "This category can identify browser errors, insecure behavior, deprecated APIs, and other implementation concerns.",
    action: "Open the page diagnostics to see which audits reduced the score.",
    related: ["Accessibility", "SEO"],
    aliases: ["BP"],
  },
  {
    id: "seo",
    term: "SEO",
    shortDefinition: "Automated checks for basic search-engine discoverability.",
    category: "scores-evidence",
    appMeaning: "The Lighthouse SEO score checks technical fundamentals such as crawlability and metadata; it does not measure rankings or content quality.",
    action: "Resolve failed audits, then use dedicated search tools for broader SEO analysis.",
    related: ["Accessibility", "Best Practices"],
    aliases: ["Search engine optimization"],
  },
  {
    id: "lcp",
    term: "LCP",
    shortDefinition: "How long it takes the page’s main visible content to appear.",
    category: "scores-evidence",
    appMeaning: "Largest Contentful Paint is available in both Lighthouse lab evidence and CrUX visitor evidence.",
    action: "Investigate the main content element, image delivery, server response, and render-blocking resources when LCP is slow.",
    related: ["Performance", "TTFB"],
    aliases: ["Largest Contentful Paint", "Main content load"],
  },
  {
    id: "inp",
    term: "INP",
    shortDefinition: "How quickly the page responds to visitor interactions.",
    category: "scores-evidence",
    appMeaning: "Interaction to Next Paint is a real-user responsiveness metric supplied by CrUX. Lighthouse uses related lab diagnostics rather than directly reproducing the field metric.",
    action: "Investigate long main-thread tasks and expensive event handling when INP is slow.",
    related: ["TBT", "Visitor experience"],
    aliases: ["Interaction to Next Paint", "Interaction responsiveness"],
  },
  {
    id: "cls",
    term: "CLS",
    shortDefinition: "How much visible content unexpectedly moves while the page loads.",
    category: "scores-evidence",
    appMeaning: "Cumulative Layout Shift is measured in Lighthouse and CrUX; lower values indicate a more visually stable page.",
    action: "Reserve space for media and embeds, and avoid inserting content above existing content.",
    related: ["Performance", "Visitor experience"],
    aliases: ["Cumulative Layout Shift", "Visual stability"],
  },
  {
    id: "ttfb",
    term: "TTFB",
    shortDefinition: "How long the browser waits for the first byte from the server.",
    category: "scores-evidence",
    appMeaning: "Time to First Byte is shown as visitor evidence and provides context for loading metrics such as LCP.",
    action: "Investigate server processing, redirects, network latency, and caching when it is slow.",
    related: ["LCP", "Visitor experience"],
    aliases: ["Time to First Byte", "Server response time"],
  },
  {
    id: "tbt",
    term: "TBT",
    shortDefinition: "How much time the main thread is blocked during a Lighthouse test.",
    category: "scores-evidence",
    appMeaning: "Total Blocking Time is a lab metric that helps diagnose responsiveness problems and is related to, but not the same as, real-user INP.",
    action: "Reduce long JavaScript tasks, third-party work, and expensive main-thread processing.",
    related: ["INP", "Performance"],
    aliases: ["Total Blocking Time"],
  },
  {
    id: "agent-readiness",
    term: "Agent readiness",
    shortDefinition: "Checks that show whether a page is understandable and usable by automated agents.",
    category: "scores-evidence",
    appMeaning: "Page Watch evaluates discoverability, structure, semantics, forms, metadata, and related signals independently from Lighthouse category scores. The Agent-readiness tab leads with a verdict for the page rather than a score, and the individual check results sit beneath it as one of the supporting sources.",
    action: "Open the page’s agent-readiness evidence, read the verdict and its primary issue, then work down the issue list.",
    related: ["Agent access verdict", "Agent access issue", "External agent audit", "Page detail"],
  },
  {
    id: "agent-access-verdict",
    term: "Agent access verdict",
    shortDefinition: "Page Watch’s single conclusion about whether agents can use a page.",
    category: "scores-evidence",
    appMeaning: "Ready means nothing determined is failing. Needs attention means there are issues but none of them is an essential blocker. Blocked means at least one essential check is failing, so agents cannot use the page properly. Unknown means no source could determine a result yet. The verdict is Page Watch’s own judgement across every source; it is never an average of the underlying scores.",
    action: "Treat Blocked as work to schedule now, and Unknown as a signal that evidence is missing rather than that the page is fine.",
    related: ["Agent readiness", "Agent access issue", "Essential blocker"],
    aliases: ["Ready", "Needs attention", "Blocked"],
  },
  {
    id: "agent-access-issue",
    term: "Agent access issue",
    shortDefinition: "One problem, with every source that reported it kept underneath.",
    category: "scores-evidence",
    appMeaning: "Page Watch’s own HTTP checks, the rendered-page probe, and the external audit often describe the same problem in different words and at different scopes. An issue merges them into one entry showing what happened, why it matters to an agent, what to do, how confident Page Watch is, and which sources agree. When sources disagree, both readings are shown rather than averaged.",
    action: "Expand an issue to see its sources and confidence before deciding whether to act on it.",
    related: ["Agent access verdict", "External agent audit", "Essential blocker", "Not applicable"],
  },
  {
    id: "essential-blocker",
    term: "Essential blocker",
    shortDefinition: "A failing check that agents cannot work around.",
    category: "scores-evidence",
    appMeaning: "An issue is an essential blocker when it is both essential-tier and currently failing. Essential blockers are added to your Inbox automatically because they stop agents using the site; other issues stay on the Agent-readiness tab until you add them to Tasks yourself. A partial result on an essential check is a real problem but is not counted as a blocker.",
    action: "Clear essential blockers before spending time on recommended improvements.",
    related: ["Agent access verdict", "Agent access issue", "Partial"],
  },
  {
    id: "external-agent-audit",
    term: "External agent audit",
    shortDefinition: "An independent, origin-level agent-readiness audit from Ora.",
    category: "scores-evidence",
    appMeaning: "Ora is the scanner behind Is Agentic, and Page Watch shows the Is Agentic essentials reading by default with Ora’s own score under advanced evidence. The two use different scales and are never averaged with each other or with Page Watch’s check percentage. An audit covers a whole origin, so every watched page on that origin shares one reading, unlike Page Watch checks and the rendered-page probe, which are page-level. Ora scans are public: a result is stored in Ora’s directory and can appear in its leaderboard and research statistics, so a project must opt in before anything is sent. Webflow staging domains are never sent.",
    action: "Enable it in Watch List settings if you want independent corroboration, then refresh an audit from a page’s Agent-readiness tab.",
    related: ["Agent access issue", "Verifying a fix", "Not applicable", "Agent readiness"],
    aliases: ["Ora", "Is Agentic", "Essentials score"],
  },
  {
    id: "agent-verification",
    term: "Verifying a fix",
    shortDefinition: "Re-running only the provider checks a task recorded.",
    category: "recommendations-tasks",
    appMeaning: "When you complete an agent-access task, Page Watch asks the external provider to re-run just the checks that task recorded. If they all pass, or become correctly not applicable, the issue is resolved. If any is still failing or partial, the issue is returned and the task moves back into open work. If the provider cannot answer, the issue stays Verifying and can be retried — provider silence is never treated as proof that your fix did not work.",
    action: "Complete the task as usual; the re-check runs on its own alongside the existing 2/7/30-day follow-ups.",
    related: ["External agent audit", "Agent access issue", "Change marker"],
  },
  {
    id: "not-applicable",
    term: "Not applicable",
    shortDefinition: "Evidence that a check does not apply, which is different from ignoring it.",
    category: "scores-evidence",
    appMeaning: "Not applicable is supplied by a source that determined the check does not apply to this product, for example a payment protocol on a site that sells nothing. Ignored is your own policy decision to stop counting a check. Unavailable means a source could not determine a result at all, and Partial means a check is genuinely half-met. Page Watch keeps all four distinct rather than collapsing them into pass or fail.",
    action: "Prefer Not applicable evidence over ignoring a check, so the reason stays visible to everyone.",
    related: ["Agent access issue", "Ignored", "Partial"],
    aliases: ["Unavailable", "Partial"],
  },
  {
    id: "reliable",
    term: "Reliable",
    shortDefinition: "The collection has enough unique, warning-free samples to trust.",
    category: "scores-evidence",
    appMeaning: "Reliable is the highest Lighthouse collection-quality status.",
    action: "Use the median, range, and promoted findings normally.",
    related: ["Low confidence", "Unusable", "Median"],
  },
  {
    id: "low-confidence",
    term: "Low confidence",
    shortDefinition: "The evidence is usable but has limitations that deserve caution.",
    category: "scores-evidence",
    appMeaning: "Fewer eligible runs, warnings, or variability can reduce confidence in scores or findings.",
    action: "Look at the sample range and repeat the collection before acting on a marginal change.",
    related: ["Reliable", "Unusable", "Range"],
  },
  {
    id: "unusable",
    term: "Unusable",
    shortDefinition: "The evidence does not meet the minimum standard for a trusted result.",
    category: "scores-evidence",
    appMeaning: "Page Watch excludes unusable evidence from normal status decisions.",
    action: "Retry later and investigate repeated provider warnings or page failures.",
    related: ["Inconclusive", "Low confidence"],
  },
  {
    id: "recommendation",
    term: "Recommendation",
    shortDefinition: "A potential improvement supported by recurring measurement evidence.",
    category: "recommendations-tasks",
    appMeaning: "Recommendations can come from Lighthouse, detected Webflow-native elements, or exact-URL visitor problems that are not reproduced in the lab.",
    action: "Review the evidence, likely impact, actionability, and effort before choosing Task or Ignore.",
    related: ["Inbox", "Tasks", "Ignored"],
  },
  {
    id: "ignored",
    term: "Ignored",
    shortDefinition: "A recommendation intentionally removed from the active workflow.",
    category: "recommendations-tasks",
    appMeaning: "Ignoring records that the finding was reviewed but should not become a task.",
    action: "Use it for irrelevant, accepted, duplicate, or non-actionable findings—not simply to hide uncertain evidence.",
    related: ["Recommendation", "Inbox"],
  },
  {
    id: "to-do",
    term: "To do",
    shortDefinition: "A task that has been accepted but not started.",
    category: "recommendations-tasks",
    appMeaning: "This is the initial status when an Inbox recommendation becomes a task.",
    action: "Start it when someone begins the work.",
    related: ["In progress", "Done", "Tasks"],
  },
  {
    id: "in-progress",
    term: "In progress",
    shortDefinition: "A task that is currently being worked on.",
    category: "recommendations-tasks",
    appMeaning: "The recommendation remains linked to its original page and evidence while work is underway.",
    action: "Mark it Done after the relevant change is actually made, or move it back to To do if work stops.",
    related: ["To do", "Done", "Tasks"],
  },
  {
    id: "done",
    term: "Done",
    shortDefinition: "A task whose associated change has been completed.",
    category: "recommendations-tasks",
    appMeaning: "Completing a task adds a dated change marker to the page and allows scheduled 2-, 7-, and 30-day follow-up comparisons.",
    action: "Only mark work Done after the change is live so later measurements line up with the marker.",
    related: ["Change marker", "In progress", "Follow-up"],
  },
  {
    id: "change-marker",
    term: "Change marker",
    shortDefinition: "A dated note showing when a meaningful page change happened.",
    category: "recommendations-tasks",
    appMeaning: "Markers appear alongside page history so score movement can be compared with releases, fixes, experiments, or completed tasks.",
    action: "Use a clear description and the date the change became effective.",
    related: ["Done", "Performance trend", "Follow-up"],
  },
  {
    id: "follow-up",
    term: "Follow-up",
    shortDefinition: "A later comparison that checks the result of a recorded change.",
    category: "recommendations-tasks",
    appMeaning: "Page Watch can report 2-, 7-, and 30-day comparisons after a completed task’s change marker.",
    action: "Use follow-ups to validate impact rather than assuming completion produced an improvement.",
    related: ["Change marker", "Done"],
  },
  {
    id: "active-field-issue",
    term: "Active field issue",
    shortDefinition: "A real-visitor problem that is currently outside the Good range.",
    category: "recommendations-tasks",
    appMeaning: "This status is used for exact-URL CrUX evidence that Lighthouse does not currently reproduce.",
    action: "Treat it as real visitor impact, while investigating why the lab and field evidence differ.",
    related: ["Visitor experience", "Verifying recovery", "Corroborated"],
  },
  {
    id: "verifying-recovery",
    term: "Verifying recovery",
    shortDefinition: "One good visitor-data window has appeared, but another is required to confirm resolution.",
    category: "recommendations-tasks",
    appMeaning: "Page Watch waits for two distinct good CrUX windows because each window covers a rolling period.",
    action: "Continue monitoring; do not close the issue based on the first good window alone.",
    related: ["Active field issue", "Field issue resolved"],
  },
  {
    id: "field-issue-resolved",
    term: "Field issue resolved",
    shortDefinition: "Two distinct visitor-data windows confirm that the issue is back in the Good range.",
    category: "recommendations-tasks",
    appMeaning: "The field-only recommendation remains documented even though its current lifecycle is resolved.",
    action: "Review the associated changes and continue normal monitoring.",
    related: ["Verifying recovery", "Field issue returned"],
  },
  {
    id: "corroborated",
    term: "Corroborated",
    shortDefinition: "A visitor problem is now also reproduced or explained by lab evidence.",
    category: "recommendations-tasks",
    appMeaning: "Independent evidence systems now support the same performance concern.",
    action: "Prioritize the issue and use the Lighthouse diagnostics to investigate likely causes.",
    related: ["Active field issue", "Lab and field"],
  },
  {
    id: "field-issue-returned",
    term: "Field issue returned",
    shortDefinition: "A visitor problem reappeared after it had cleared or become corroborated.",
    category: "recommendations-tasks",
    appMeaning: "The regression is retained as part of the recommendation’s field-evidence lifecycle.",
    action: "Review changes since resolution and reopen related work when appropriate.",
    related: ["Field issue resolved", "Active field issue"],
  },
  {
    id: "project-viewer",
    term: "Project viewer",
    shortDefinition: "A user who can inspect a project without managing it.",
    category: "access-roles",
    appMeaning: "Viewers can access the project’s monitoring information but do not receive project-administration controls.",
    action: "Ask a project administrator when watchlist, settings, or membership changes are needed.",
    related: ["Project administrator", "App administrator"],
  },
  {
    id: "project-administrator",
    term: "Project administrator",
    shortDefinition: "A user who can view and manage one project.",
    category: "access-roles",
    appMeaning: "Project administrators receive management controls for their assigned project, including its watchlist, settings, and members.",
    action: "Use administrative access carefully because monitoring configuration affects the whole project.",
    related: ["Project viewer", "App administrator"],
    aliases: ["Project admin"],
  },
  {
    id: "app-administrator",
    term: "App administrator",
    shortDefinition: "A user who can administer Page Watch across projects.",
    category: "access-roles",
    appMeaning: "App administrators can access project-management and app-administration capabilities without needing a membership record for every project.",
    action: "Use this role only for people responsible for the application as a whole.",
    related: ["Project administrator", "Project viewer"],
    aliases: ["App admin"],
  },
];
