export type { ExtensionProvidedApiDefinition, ExtensionProvidedApiHandler, ExtensionProvidedApiHandlerContext, ExtensionProvidedApiHandlerMap, ExtensionProvidedApiHandlers, ExtensionProvidedApiMapConstraint, ExtensionProvidedApiMethodDefinition, UntypedExtensionProvidedApiMap, } from "./extension-provided-api";
export type { AgentRunParams, AgentRunProgressDataReader, AgentRunResultDataReader, CapabilityIntentDefinition, CapabilityScopeString, CodeMapNodeToSourceParams, CodeMapNodeToSourceResultDataReader, CodeApplyFileEditOkOutcome, CodeApplyFileEditParams, CodeApplyFileEditOutcome, CodeApplyFileEditResultDataReader, CodeReadFileParams, CodeReadFileResultDataReader, CodeSourceLocationReader, CodeSourceRange, ContentGetItemParams, ContentGetItemResultDataReader, ContentGetTypeParams, ContentGetTypeResultDataReader, ContentItem, ContentItemReader, ContentItemRef, ContentItemSummary, ContentItemSummaryReader, ContentListSourcesParams, ContentListSourcesResultDataReader, ContentListTypesParams, ContentListTypesResultDataReader, ContentNormalizationLimits, ContentQueryItemsParams, ContentQueryItemsResultDataReader, ContentSource, ContentSourceReader, ContentType, ContentTypeReader, ContentTypeSummary, ContentTypeSummaryReader, ContentValue, ContentValueReader, ContextActor, ContextActorReader, ContextAppendParams, ContextAppendResultData, ContextFactAppendedParams, ContextFact, ContextGetParams, ContextGetResultData, ContextQueryParams, ContextQueryResultData, ContextRef, ContextRefReader, ContextRetention, ContextSource, ContextSourceReader, ExtensionUiOpenParams, ExtensionUiOpenResultData, ExtensionUiPostMessageParams, ExtensionUiPostMessageResultData, PreviewArtifactTarget, PreviewReadConsoleParams, PreviewReadConsoleProgressDataReader, PreviewReadConsoleResultDataReader, PreviewOpenArtifactParams, PreviewOpenArtifactResultData, PreviewReloadParams, PreviewReloadResultDataReader, PreviewOpenTargetParams, PreviewOpenTargetResultDataReader, PreviewOpenRouteParams, PreviewOpenRouteResultDataReader, ProjectGetInfoParams, ProjectGetInfoResultDataReader, RuntimeHealthChangedParams, RuntimeGetHealthParams, RuntimeHealthResultDataReader, SelectedSelectionReader, SelectionSetParams, SelectionSetResultDataReader, SelectionChangedParams, SelectionGetCurrentParams, SelectionStateReader, TypedCapabilities, TypedCapabilityMethod, } from "./capability-contracts";
export type { ExtensionActivate, ExtensionContext, ExtensionContributionRegistration, ExtensionRegistrationDiagnostic, ExtensionRegistrationResult, ExtensionProvidedApiActivate, ExtensionProvidedApiContext, ExtensionProvidedApiRegistration, ExtensionToolContributionRegistration, ExtensionUiContributionOptions, ExtensionUiContributionRegistration, ExtensionViewIntentDispatch, ExtensionViewIntentHandler, ExtensionViewIntentHandlerContext, UntypedExtensionViewIntentHandler, } from "./extension";
export type { ExtensionIntentData, ExtensionIntentDefinition, ExtensionIntentMapConstraint, ExtensionIntentName, ExtensionIntentParams, ExtensionIntentParamsOptional, ExtensionIntentParamsProperty, UntypedExtensionIntentMap, } from "./intent-map";
export { createTypedCapabilities, matchTypedCapabilityResult } from "./runtime";
export { isContentConnectionRequiredResult } from "./content-connection-required-result";
export type { ContentConnectionRequiredResultDataReader, ContentConnectionRequiredResultReader, } from "./content-connection-required-result";
export { CONTENT_ITEM_CONTEXT_REF_CODEC_VERSION, CONTENT_ITEM_CONTEXT_REF_MAX_ID_LENGTH, CONTENT_ITEM_CONTEXT_REF_TYPE, CONTENT_ITEM_REF_IDENTIFIER_MAX_LENGTH, decodeContentItemContextRef, encodeContentItemContextRef, } from "./content-item-context-ref";
export type { BlockedResultReader, CapabilityResult, ExtensionDisposable, JsonObject, JsonValue, AnyCapabilityOutcome, NeedsInputResult, OkResult, ReadonlyJsonObject, ReadonlyJsonValue, ReadonlyToolAnnotations, ReadonlyToolDescriptor, ReviewableChangeRef, ToolAnnotations, ToolDescriptor, CapabilityOutcome, CapabilityProducerOutcome, TypedCapabilityResult, CapabilityOutcomeHandlers, CapabilityOkOutcome, } from "./shared";
